// <auto-generated />
using LocalBusinessApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalBusinessApi.Migrations
{
    [DbContext(typeof(LocalBusinessApiContext))]
    [Migration("20211120024936_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LocalBusinessApi.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            Category = "Restaurant",
                            Description = "A Chinese resturant that sells authentic Sichuan food.",
                            Name = "Taste of Sichuan",
                            Rate = 5,
                            Review = "Love Taste of Sichuan! My favorite item on the menu is the potstickers. They are hand-made and taste like they are made with love. I also love the wontons in chili oil. Highly recommend this place for great Sichuan-style Chinese food in Beaverton."
                        },
                        new
                        {
                            BusinessId = 2,
                            Category = "Restaurant",
                            Description = "American chain restaurant offering sizable portions from a vast menu including signature cheesecake",
                            Name = "The Cheesecake Factory",
                            Rate = 4,
                            Review = "Consistent each time. No wonder the long wait times esp on weekends. Try blocking a table 5o save you time! Whatever you eat, ensure you keep enough space for the two page dessert options."
                        },
                        new
                        {
                            BusinessId = 3,
                            Category = "Shop",
                            Description = "Candies & chocolates are sold by the piece or box at this old-school chain, in business since 1921.",
                            Name = "See's Candies",
                            Rate = 3,
                            Review = "Apple pie white chocate truffles are the best! And blueberry truffles too!"
                        },
                        new
                        {
                            BusinessId = 4,
                            Category = "Shop",
                            Description = "Toy store in Southgate CPO, Oregon",
                            Name = "Go! Calendars, Toys & Games",
                            Rate = 2,
                            Review = "A lot of variety here. The store is not well lit though and feels cluttered. They do have toys for every age child. Prices are reasonable."
                        },
                        new
                        {
                            BusinessId = 5,
                            Category = "Resturant",
                            Description = "Fast-food chain for Chinese standards, including some health-conscious options.",
                            Name = "Nori Japan",
                            Rate = 1,
                            Review = "The food is overpriced  for the small amount of food, rice was really old, and the lady was really rude."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
